package model;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;


public class FarmerModule{

    public FarmerModule() throws SQLException {
    }

    public class User {
        int id;//for farmer either provide a guide line or just return what the user enters adding fr to the front and the buyer by
        String userName;//no same userName
        String name;
        String location;
        String email;
        String password;
        int phoneNumber;

        public User(int id,String userName, String name,String location, String email,int phoneNumber){
            this.id=id;
            this.userName=userName;
            this.name=name;
            this.location=location;
            this.email=email;
            this.password=password;
            this.phoneNumber=phoneNumber;
        }
        public String setEmail(){
            String regex="^[A-Za-z0-9_+-]+@[A-Za-z0-9]+//.[A-Za-z]{2,}$";
            Pattern pattern=Pattern.compile(regex);
            Matcher matcher=pattern.matcher(email);
            boolean isMatch=matcher.find();
            if(isMatch){
                this.email=email;
                return email;
            }
            else{
                System.out.println("invalid email!");
                return "";
            }
        }
        public String setPassword(){
            String regex="[A-Za-z][0-9][_+-@#$%^&*!]";
            Pattern pattern=Pattern.compile(regex);
            Matcher matcher=pattern.matcher(password);
            boolean isMatch=matcher.find();
            if (isMatch){
                this.password=password;
                return password;
            }
            else{
                System.out.println("invalid password!");
                return"";
//when u ask the user to enter the password and the email specially the password also provide the criterion for each
            }
        }
        public int setPhoneNumber() {
            if (String.valueOf(this.phoneNumber).length() > 10 || String.valueOf(this.phoneNumber).length() < 10) {
                System.out.println("invaid phone number");
                return 0;
            } else {
                return this.phoneNumber;
            }
        }
    }
    Connection conn = DriverManager.getConnection("jdbc:sqlite:agriconnect.db");
    Statement stmt = conn.createStatement();
    stmt.executeUpdate(
            "CREATE TABLE IF NOT EXISTS users (" +
            "id INTEGER PRIMARY KEY, " +
            "userName TEXT UNIQUE, " +
            "name TEXT, " +
            "email TEXT UNIQUE, " +
            "password TEXT)"
        );
    // Check if ID exists
    PreparedStatement checkIdStmt = conn.prepareStatement(
            "SELECT COUNT(*) FROM users WHERE id = ?"
    );
    checkIdStmt.setInt(1, newUser.getId());
        ResultSet rsId = checkIdStmt.executeQuery();
    rsId.next();
        int idCount = rsId.getInt(1);

    // Check if username exists
    PreparedStatement checkUserStmt = conn.prepareStatement(
            "SELECT COUNT(*) FROM users WHERE userName = ?"
    );
    checkUserStmt.setString(1, newUser.setUserName());
        ResultSet rsUser = checkUserStmt.executeQuery();
    rsUser.next();
        int userCount = rsUser.getInt(1);

// Decide based on results
    if (idCount > 0) {
        System.out.println("Error: This ID is already taken!");
    } else if (userCount > 0) {
        System.out.println("Error: This username is already taken!");
    } else {
        // Safe to insert new user
        PreparedStatement insertStmt = conn.prepareStatement(
                "INSERT INTO users (id, userName, name, email, password) VALUES (?, ?, ?, ?, ?)"
        );
        insertStmt.setInt(1, newUser.getId());
        insertStmt.setString(2, newUser.getUserName());
        insertStmt.setString(3, newUser.getName());
        insertStmt.setString(4, newUser.getEmail());
        insertStmt.setString(5, newUser.getPassword());
        insertStmt.executeUpdate();

        System.out.println("User registered successfully!");
    }
    Statement statem= conn.createStatement();
    stmt.executeUpdate(
        "CREATE TABLE IF NOT EXISTS items (" +
        "itemId INTEGER PRIMARY KEY, " +
        "userId INTEGER, " +                 // link to users table
        "itemName TEXT, " +
        "itemDescription TEXT, " +"itemCost INTEGER"+
        "FOREIGN KEY(userId) REFERENCES users(id))"
        );
    PreparedStatement insertItem = conn.prepareStatement(
            "INSERT INTO items (itemId, userId, itemName, itemDescription) VALUES (?, ?, ?, ?)"
    );
    insertItem.setInt(1, 101);                  // itemId
    insertItem.setInt(2, newUser.getId());      // link to user
    insertItem.setString(3, "Corn Seeds");      // itemName
    insertItem.setString(4, "High-yield hybrid corn seeds"); // itemDescription
    insertItem.executeUpdate();
}




# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
